/**
 * Converts the vendored Cburnett SVGs (assets/pieces/cburnett, GPLv2+, Colin M.L. Burnett)
 * into themeable geometry: every element's inherited paint is resolved and mapped to a
 * semantic role, so a theme restyles the set through CSS variables instead of hex colours.
 *
 *   body   - the piece's main surface
 *   ink    - outlines and dark details
 *   detail - the light inner lines on dark pieces
 *
 * Output: src/pieces/geometry.generated.ts. Re-run after changing the sources:
 *   node scripts/build-pieces.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "assets", "pieces", "cburnett");
const OUT = path.join(ROOT, "src", "pieces", "geometry.generated.ts");

const SHAPES = new Set(["path", "circle"]);
const INHERITED = ["fill", "stroke", "stroke-width", "stroke-linecap", "stroke-linejoin", "fill-rule"];
const GEOMETRY = { path: ["d"], circle: ["cx", "cy", "r"] };

/** Minimal parser for these simple, text-free SVGs. */
function parse(svg) {
  const root = { tag: "#root", attrs: {}, children: [] };
  const stack = [root];
  for (const m of svg.matchAll(/<(\/?)([a-z]+)([^>]*?)(\/?)>/g)) {
    const [, closing, tag, rawAttrs, selfClosing] = m;
    if (closing) {
      stack.pop();
      continue;
    }
    const attrs = Object.fromEntries([...rawAttrs.matchAll(/([a-z-]+)="([^"]*)"/g)].map((a) => [a[1], a[2]]));
    const node = { tag, attrs, children: [] };
    stack.at(-1).children.push(node);
    if (!selfClosing) stack.push(node);
  }
  return root;
}

function role(color, kind, side) {
  const c = (color ?? "").toLowerCase();
  if (c === "none" || c === "") return null;
  if (c === "#ececec") return "detail";
  if (c === "#fff" || c === "#ffffff") return side === "w" ? "body" : "detail";
  if (c === "#000" || c === "#000000") {
    // On a dark piece a black fill *is* the body; everywhere else black is ink.
    return side === "b" && kind === "fill" ? "body" : "ink";
  }
  throw new Error(`unmapped ${kind} colour ${color}`);
}

function flatten(node, inherited, side, out) {
  const own = {};
  for (const k of INHERITED) if (node.attrs[k] !== undefined) own[k] = node.attrs[k];
  const style = { ...inherited, ...own };

  if (SHAPES.has(node.tag)) {
    const el = { tag: node.tag };
    for (const k of GEOMETRY[node.tag]) el[k] = node.attrs[k];
    // SVG defaults: fill black, stroke none.
    el.fill = role(style.fill ?? "#000", "fill", side);
    el.stroke = role(style.stroke ?? "none", "stroke", side);
    if (el.stroke) {
      el.strokeWidth = Number(style["stroke-width"] ?? 1);
      el.linecap = style["stroke-linecap"] ?? "butt";
      el.linejoin = style["stroke-linejoin"] ?? "miter";
    }
    if (style["fill-rule"]) el.fillRule = style["fill-rule"];
    if (el.fill || el.stroke) out.push(el);
  }
  for (const child of node.children) flatten(child, style, side, out);
}

const pieces = {};
for (const file of readdirSync(SRC).filter((f) => f.endsWith(".svg")).sort()) {
  const key = path.basename(file, ".svg");
  const side = key[0];
  const out = [];
  flatten(parse(readFileSync(path.join(SRC, file), "utf8")), {}, side, out);
  pieces[key] = out;
}

const keys = Object.keys(pieces);
if (keys.length !== 12) throw new Error(`expected 12 pieces, found ${keys.length}`);

const banner = `// GENERATED by scripts/build-pieces.mjs from assets/pieces/cburnett - do not edit.
// Geometry: Cburnett chess pieces by Colin M.L. Burnett, GPLv2+.
// https://commons.wikimedia.org/wiki/Category:SVG_chess_pieces
`;
const body = `export type PieceRole = "body" | "ink" | "detail";

export interface PieceElement {
  tag: "path" | "circle";
  d?: string;
  cx?: string;
  cy?: string;
  r?: string;
  fill: PieceRole | null;
  stroke: PieceRole | null;
  strokeWidth?: number;
  linecap?: "butt" | "round" | "square";
  linejoin?: "miter" | "round" | "bevel";
  fillRule?: "evenodd" | "nonzero";
}

export const PIECE_GEOMETRY: Record<string, PieceElement[]> = ${JSON.stringify(pieces, null, 2)};
`;
writeFileSync(OUT, banner + body);

const summary = keys.map((k) => `${k}:${pieces[k].length}`).join(" ");
console.log(`wrote ${path.relative(ROOT, OUT)} (${summary})`);
